

DROP TABLE EMPLEADO CASCADE CONSTRAINT;
DROP TABLE SEDE CASCADE CONSTRAINT;
DROP TABLE TARIFA_INTERNET CASCADE CONSTRAINT;
DROP TABLE TARIFA_TELEFONO CASCADE CONSTRAINT;
DROP TABLE CLIENTE CASCADE CONSTRAINT;
DROP TABLE PROMOCION CASCADE CONSTRAINT;
DROP TABLE COMERCIAL CASCADE CONSTRAINT;
DROP TABLE TECNICO CASCADE CONSTRAINT;
DROP TABLE OFICINA CASCADE CONSTRAINT;
DROP TABLE OFICINISTA CASCADE CONSTRAINT;
DROP TABLE CONTRATO CASCADE CONSTRAINT;
DROP TABLE SERVICIO CASCADE CONSTRAINT;
DROP TABLE AVERIA CASCADE CONSTRAINT;
DROP TABLE REPARA CASCADE CONSTRAINT;
DROP TABLE TELEFONO CASCADE CONSTRAINT;
DROP TABLE INTERNET CASCADE CONSTRAINT;
DROP TABLE OFERTA CASCADE CONSTRAINT;
DROP PROCEDURE IMPRIMIRINGRESOS;
DROP PROCEDURE ASIGNARTECNICO;
DROP PROCEDURE INFORMECLIENTE;
DROP PROCEDURE INFORMECOMERCIAL;
DROP PROCEDURE INFORMEEMPRESA;
DROP FUNCTION GENERARREPORTEINGRESOS;
DROP FUNCTION INGRESOSOFERTAS;
DROP FUNCTION GASTOSCLIENTE;
