CONNECT system/bdadmin;

CREATE USER p3COMERCIAL IDENTIFIED BY p3COMERCIAL;
GRANT CONNECT, RESOURCE, CREATE VIEW TO p3COMERCIAL;

CREATE USER p3AGENTE IDENTIFIED BY p3AGENTE;
GRANT CONNECT, RESOURCE, CREATE VIEW TO p3AGENTE;

connect p3COMECRIAL/p3COMERCIAL;

CREATE VIEW INFORMACIONCOMERCIAL
AS 
SELECT c.codigo, count(*)
FROM OFERTA O, COMERCIAL C
WHERE C.CODIGO = O.CODIGO
GROUP BY c.codigo
ORDER BY COUNT(*);

GRANT SELECT ON INFORMACIONCOMERCIAL TO p3AGENTE WITH GRANT OPTION;